# Generated by Django 3.2.7 on 2024-01-28 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fee',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='user',
            name='trans_fee',
            field=models.IntegerField(default=100),
        ),
    ]
