# Generated by Django 3.2.7 on 2024-03-12 20:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20240128_1106'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amznurl', models.CharField(default='', max_length=500)),
                ('price', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='fee',
        ),
        migrations.RemoveField(
            model_name='user',
            name='trans_fee',
        ),
        migrations.AddField(
            model_name='user',
            name='ngwords',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.CreateModel(
            name='Fee',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('multirate', models.IntegerField(default=100)),
                ('shipfee', models.IntegerField(default=0)),
                ('fee', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='FeeUser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
