# Generated by Django 3.2.7 on 2024-03-12 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20240313_0502'),
    ]

    operations = [
        migrations.AddField(
            model_name='fee',
            name='feetype',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='fee',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
