# Generated by Django 3.2.7 on 2024-03-12 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20240313_0524'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fee',
            old_name='feetype',
            new_name='fee_type',
        ),
        migrations.RenameField(
            model_name='fee',
            old_name='multirate',
            new_name='multi_rate',
        ),
        migrations.RenameField(
            model_name='fee',
            old_name='shipfee',
            new_name='ship_fee',
        ),
        migrations.RemoveField(
            model_name='fee',
            name='user',
        ),
    ]
