# Generated by Django 3.2.7 on 2024-03-12 20:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20240313_0537'),
    ]

    operations = [
        migrations.AddField(
            model_name='fee',
            name='fee_user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='fee_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='product',
            name='product_user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='product_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
