# Generated by Django 3.2.7 on 2024-03-22 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20240313_0542'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='ftpname',
            new_name='storename',
        ),
        migrations.RemoveField(
            model_name='user',
            name='ftppassword',
        ),
    ]
