# Generated by Django 3.2.7 on 2024-04-15 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20240415_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='access_token',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
    ]
