# Generated by Django 3.2.7 on 2024-05-03 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_product_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='fee',
            name='store_type',
            field=models.CharField(default='Yahoo', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='store_type',
            field=models.CharField(default='Yahoo', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='enable_qoo10',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='qoo10_api_key',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='qoo10_ska',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
    ]
