# Generated by Django 3.2.7 on 2024-05-06 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20240504_0000'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='enable_qoo10',
            new_name='qoo10_enable',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='access_token',
            new_name='yahoo_access_token',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='client_id',
            new_name='yahoo_client_id',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='client_secret',
            new_name='yahoo_client_secret',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='enable_yahoo',
            new_name='yahoo_enable',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='refresh_token',
            new_name='yahoo_refresh_token',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='storename',
            new_name='yahoo_store_id',
        ),
    ]
