# Generated by Django 3.2.7 on 2024-05-06 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20240507_0346'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='qoo10_ska',
            new_name='qoo10_sak',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='qoo10_storename',
            new_name='qoo10_store_name',
        ),
    ]
