# Generated by Django 3.2.7 on 2024-06-13 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20240507_0350'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='amazon_access_token',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='amazon_client_id',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='amazon_client_secret',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='amazon_enable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='amazon_marketplace_id',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='amazon_refresh_token',
            field=models.CharField(default='', max_length=255),
        ),
    ]
