# Generated by Django 3.2.7 on 2024-06-16 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_remove_user_amazon_marketplace_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='code',
            field=models.CharField(default='', max_length=255),
        ),
    ]
