# Generated by Django 3.2.7 on 2024-06-20 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_product_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='qty',
            field=models.BooleanField(default=True),
        ),
    ]
