# Generated by Django 3.2.7 on 2024-06-24 09:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_product_qty'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='qoo10_update_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 27, 0, 0)),
        ),
        migrations.AddField(
            model_name='user',
            name='yahoo_update_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 27, 0, 0)),
        ),
    ]
