# Generated by Django 3.2.7 on 2024-06-26 12:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20240624_1834'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='', max_length=255)),
                ('content', models.TextField(default='')),
                ('url', models.CharField(default='', max_length=255)),
                ('created_at', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
