# Generated by Django 5.0.6 on 2024-07-08 14:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_alter_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='NgWord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ngword', models.CharField(default='', max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
