# Generated by Django 5.0.6 on 2024-07-09 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_ngword'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ng_asin_codes',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='ng_descriptions',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='ng_titles',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='ngwords',
            field=models.TextField(blank=True, default='', max_length=255, null=True),
        ),
    ]
