# Generated by Django 5.0.6 on 2024-07-09 23:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_user_ng_asin_codes_user_ng_descriptions_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PushServiceGlobalSetting',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='default', max_length=255)),
                ('ng_asin_codes', models.TextField(blank=True, default='', null=True)),
                ('ng_titles', models.TextField(blank=True, default='', null=True)),
                ('ng_descriptions', models.TextField(blank=True, default='', null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.DeleteModel(
            name='NgWord',
        ),
    ]
