# Generated by Django 5.0.6 on 2024-08-20 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_pushserviceglobalsetting_delete_ngword'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='remain_score',
            field=models.IntegerField(default=5),
        ),
    ]
