# Generated by Django 5.0.6 on 2024-08-20 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_user_remain_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quanty',
            field=models.IntegerField(default=5),
        ),
    ]
