# Generated by Django 5.0.6 on 2024-08-23 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_product_quanty'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='seller_count',
            field=models.IntegerField(default=1),
        ),
    ]
