# Generated by Django 5.0.6 on 2024-09-02 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_user_seller_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='oneseller',
            field=models.IntegerField(default=True),
        ),
    ]
