# Generated by Django 5.0.6 on 2024-09-13 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_user_oneseller'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='auto',
            field=models.BooleanField(default=False),
        ),
    ]
