# Generated by Django 5.0.6 on 2024-09-26 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_user_auto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='auto',
            field=models.IntegerField(default=-1),
        ),
    ]
