# Generated by Django 5.0.6 on 2024-10-17 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_alter_user_auto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='auto',
            new_name='qoo10_auto',
        ),
        migrations.AddField(
            model_name='user',
            name='yahoo_auto',
            field=models.IntegerField(default=-1),
        ),
    ]
