# Generated by Django 5.0.6 on 2024-10-22 01:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_rename_auto_user_qoo10_auto_user_yahoo_auto'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='qoo10_register_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 27, 0, 0)),
        ),
        migrations.AddField(
            model_name='user',
            name='yahoo_register_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 27, 0, 0)),
        ),
    ]
