# Generated by Django 5.0.6 on 2024-10-22 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_user_qoo10_register_time_user_yahoo_register_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='multi',
            field=models.BooleanField(default=True),
        ),
    ]
