# Generated by Django 5.0.6 on 2024-10-31 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_user_multi'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='path',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='second_sub_cat',
            field=models.CharField(default='', max_length=255),
        ),
    ]
